name: Sandbox-Advanced-Resource-Group
version: 1.0.0
summary: Advanced sandbox environment with owner permission
description: Deploys an advanced sandbox environment
runner: Bicep
templatePath: main.bicep

parameters:
  - id: "vNetDeployment"
    name: "vNetDeployment"
    description: "If a vNet should be deployed"
    type: "bool"
    default: "false"
