name: VNet-TF-simple
summary: This is a deployment of a Azure VNet using TF.
description: Deploys a VNet
templatePath: main.tf
parameters:
- id: "vnet_name"
  name: "virtualNetworkNameParameter"
  description: "Vnet name"
  type: "string"
  default: "vnet-tst"
-id: "resource_group_name"
  name: "resourceGroup"
  description: "Resource Group"
  type: "string"
  default: "[resourceGroup().name]"
runner: Terraform
