name: jz-test-Advanced
version: 1.0.0
summary: Advanced sandbox environment with options of adding default resources
description: Deploys an advanced sandbox environment
runner: Bicep
templatePath: main.bicep

